### ISSUE TITLE
submodules can not open online

### ISSUE THREAD

**Issue by LangDaoAI** [python-dontrepeatyourself/Object-Detection-and-Tracking-with-YOLOv8-and-DeepSORT#1]
Hi,

deep_sort and ultralytics submodules can not open online, please confirm them.

Thanks!

**Comment by Rouizi** [comment]
Hi LangDaoAI,

Thanks for pointing this out. I confirm that these two modules can't be opened.

I solved this problem - both submodules contained a .git folder, that's why when I pushed the code to GitHub, there was this problem.
